Repository StackStorm/st2-packages, pull requests merged in 2018-04, with the labels that each got.

#541 Redact password from output
  scripts/st2_bootstrap.sh
Labels: RFR

#543 Fix CI build failure, move to CircleCI2.0
  .circle/add-itest-user.sh
  .circle/configure-postgres.sh
  .circle/configure-rabbitmq.sh
  .circle/configure-services.sh
  .circle/docker.sh
  .circle/fix-cache-permissions.sh
  circle.yml
Labels: RFR, technical debt

#544 Fix Circle deploy step
  circle.yml
Labels: bug

#549 Fix dh-virtualenv packages build, avoid updating pip to latest v10.0
  .circle/docker-compose2.sh
  packages/st2/debian/rules
  rpmspec/package_venv.spec
  scripts/install_os_packages.sh
  scripts/setup-vagrant.sh
Labels: bug

#551 Add missing dh-virtualenv fix for st2mistral
  packages/st2mistral/debian/rules
Labels: RFR, bug

#552 Add missing dh-virtualenv fix for st2mistral (v2.7)
  packages/st2mistral/debian/rules
Labels: bug

#553 Fix st2mistral smoke tests not running
  rake/spec/default/10-package_st2-consistency_spec.rb
  rake/spec/default/50-installed-cli-versions_spec.rb
  rake/spec/default/60-st2_all-services-ok_spec.rb
  rake/spec/default/65-st2mistral_actions_spec.rb
  rake/spec/spec_helper.rb
  rake/spec/spec_package_iterables.rb
Labels: RFR, bug, tests
