Repository StackStorm/st2-packages, pull requests merged in 2020-06, with the labels that each got.

#638 Remove Ubuntu Trusty
  .circleci/config.yml
  README.md
  Vagrantfile
  docker-compose.circle.yml
  docker-compose.circle2.yml
  docker-compose.yml
  packages/st2/bin/runners.sh
  packages/st2/debian/rules
  packages/st2/debian/st2.st2actionrunner-worker.upstart
  packages/st2/debian/st2.st2actionrunner.upstart
  packages/st2/debian/st2.st2api.upstart
  packages/st2/debian/st2.st2auth.upstart
  packages/st2/debian/st2.st2exporter.upstart
  packages/st2/debian/st2.st2garbagecollector.upstart
  packages/st2/debian/st2.st2notifier.upstart
  packages/st2/debian/st2.st2resultstracker.upstart
  packages/st2/debian/st2.st2rulesengine.upstart
  packages/st2/debian/st2.st2scheduler.upstart
  packages/st2/debian/st2.st2sensorcontainer.upstart
  packages/st2/debian/st2.st2stream.upstart
  packages/st2/debian/st2.st2timersengine.upstart
  packages/st2/debian/st2.st2workflowengine.upstart
  packages/st2mistral/debian/mistral-api.upstart
  packages/st2mistral/debian/mistral-server.upstart
  packages/st2mistral/debian/mistral.upstart
  rake/spec/remote_helpers.rb
  scripts/includes/common.sh
  scripts/migrate_bintray_to_pkgcloud_trusty.sh
  scripts/setup-vagrant.sh
  scripts/st2_bootstrap.sh
  scripts/st2bootstrap-deb.sh
  scripts/st2bootstrap-deb.template.sh
  scripts/st2bootstrap-el6.sh
  scripts/st2bootstrap-el7.sh
  scripts/st2bootstrap-el8.sh
Labels: enhancement

#651 Remove irrelevant EL8 chatops hack from installer
  scripts/st2bootstrap-el8.sh
  scripts/st2bootstrap-el8.template.sh
Labels: bash installer, bug

#650 Improve EL8 firewall management
  scripts/st2bootstrap-el8.sh
  scripts/st2bootstrap-el8.template.sh
Labels: bash installer, enhancement

#652 stackstorm/st2#4930 pin pip for EL8
  rpmspec/package_venv.spec
Labels: OS support, RFR, bug

#653 update EL7 and U16 to use mongod 4.0
  docker-compose.override.yml
  scripts/includes/common.sh
  scripts/st2bootstrap-deb.sh
  scripts/st2bootstrap-deb.template.sh
  scripts/st2bootstrap-el6.sh
  scripts/st2bootstrap-el7.sh
  scripts/st2bootstrap-el7.template.sh
  scripts/st2bootstrap-el8.sh
Labels: bash installer, enhancement
