Repository StackStorm/st2-packages, pull requests merged in 2020-11, with the labels that each got.

#665 -v doesn't allow you to set version
  scripts/st2_bootstrap.sh
  scripts/st2bootstrap-deb.sh
  scripts/st2bootstrap-deb.template.sh
  scripts/st2bootstrap-el7.sh
  scripts/st2bootstrap-el7.template.sh
  scripts/st2bootstrap-el8.sh
  scripts/st2bootstrap-el8.template.sh
Labels: bash installer, bug

#670 check that deployment script can be written in PWD
  scripts/st2_bootstrap.sh
Labels: enhancement

#673 Change CI webhook URL
  .circleci/config.yml
Labels: enhancement

#671 EL7 to use python3
  packages/st2/Makefile
  packages/st2/component.makefile
  packages/st2/rpm/st2.spec
  rpmspec/helpers.spec
  rpmspec/package_venv.spec
Labels: feature

#674 Adding libldap2-dev, libsasl2-dev to satisfy ldap dependencies
  packages/st2/debian/control
Labels: feature

#677 issue #5088 remove obsolete check-license
  packages/st2/debian/st2.links
  rake/spec/spec_helper.rb
Labels: enhancement

#676 st2-apply-rbac-defintions binary needs to be shipped with the st2 deb…
  packages/st2/debian/st2.links
  rake/spec/spec_helper.rb
Labels: feature
