Repository StackStorm/st2-packages, pull requests merged in 2020-08, with the labels that each got.

#646 Sync dist_utils.py with latest from st2 repo
  packages/st2/dist_utils.py
Labels: bug

#658 Remove EL6 and st2python
  packages/python/st2python.spec
  packages/st2/Makefile
  packages/st2/component.makefile
  packages/st2/conf/rhel-functions-sysvinit
  packages/st2/debian/rules
  packages/st2/rpm/st2.spec
  packages/st2/rpm/st2actionrunner-worker.init
  packages/st2/rpm/st2actionrunner.init
  packages/st2/rpm/st2api.init
  packages/st2/rpm/st2auth.init
  packages/st2/rpm/st2exporter.init
  packages/st2/rpm/st2garbagecollector.init
  packages/st2/rpm/st2notifier.init
  packages/st2/rpm/st2resultstracker.init
  packages/st2/rpm/st2rulesengine.init
  packages/st2/rpm/st2scheduler.init
  packages/st2/rpm/st2sensorcontainer.init
  packages/st2/rpm/st2stream.init
  packages/st2/rpm/st2timersengine.init
  packages/st2/rpm/st2workflowengine.init
  packages/st2mistral/Makefile
  packages/st2mistral/debian/mistral-api.init
  packages/st2mistral/debian/mistral-server.init
  packages/st2mistral/debian/mistral.init
  packages/st2mistral/rpm/mistral-api.init
  packages/st2mistral/rpm/mistral-server.init
  packages/st2mistral/rpm/mistral.init
  packages/st2mistral/rpm/st2mistral.spec
  rake/build/environment.rb
  rake/build/setup.rake
  rpmspec/helpers.spec
  rpmspec/package_venv.spec
  scripts/build_python.sh
  scripts/includes/common.sh
  scripts/st2bootstrap-deb.sh
  scripts/st2bootstrap-el7.sh
  scripts/st2bootstrap-el8.sh
Labels: breaking change, enhancement

#656 Remove st2mistral packaging and builds
  .circle/buildenv_common.sh
  .circle/buildenv_mistral.sh
  .circle/configure-postgres.sh
  .circle/configure-services.sh
  .circle/docker-compose.sh
  .circle/docker-compose2.sh
  .circleci/config.yml
  .github/ISSUE_TEMPLATE.md
  README.md
  Vagrantfile
  docker-compose.circle.yml
  docker-compose.circle2.yml
  docker-compose.override.yml
  docker-compose.yml
  packages/st2/Makefile
  packages/st2/component.makefile
  packages/st2/in-requirements.txt
  packages/st2mistral/Makefile
  packages/st2mistral/bin/mistral
  packages/st2mistral/conf/helpers-sysvinit
  packages/st2mistral/conf/logrotate.conf
  packages/st2mistral/conf/mistral.conf
  packages/st2mistral/conf/policy.json
  packages/st2mistral/conf/rhel-functions-sysvinit
  packages/st2mistral/debian/README
  packages/st2mistral/debian/README.Debian
  packages/st2mistral/debian/README.source
  packages/st2mistral/debian/changelog
  packages/st2mistral/debian/compat
  packages/st2mistral/debian/conffiles
  packages/st2mistral/debian/control
  packages/st2mistral/debian/copyright
  packages/st2mistral/debian/docs
  packages/st2mistral/debian/install
  packages/st2mistral/debian/postinst
  packages/st2mistral/debian/preinst
  packages/st2mistral/debian/rules
  packages/st2mistral/debian/source/format
  packages/st2mistral/debian/st2mistral.dirs
  packages/st2mistral/rpm/mistral-api.service
  packages/st2mistral/rpm/mistral-server.service
  packages/st2mistral/rpm/mistral.service
  packages/st2mistral/rpm/st2mistral.spec
  rake/build/environment.rb
  rake/build/package_st2mistral.rake
  rake/build/setup.rake
  rake/spec/default/50-installed-cli-versions_spec.rb
  rake/spec/default/60-st2_all-services-ok_spec.rb
  rake/spec/default/65-st2mistral_actions_spec.rb
  rake/spec/spec_helper.rb
  rake/spec/spec_package_iterables.rb
  scripts/setup-vagrant.sh
Labels: breaking change, feature

#633 Make sure "postrm purge" command correctly cleans up
  packages/st2/debian/postrm
Labels: enhancement
