Repository StackStorm/st2-packages, pull requests merged in 2020-12, with the labels that each got.

#679 Build ST2 on Ubuntu 16 with Python 3
  .circleci/config.yml
  packages/st2/Makefile
  packages/st2/component.makefile
  packages/st2/debian/rules
  rake/spec/default/50-installed-cli-versions_spec.rb
Labels: enhancement

#681 Ubuntu Xenial Warning: Block python3.6 PPA installation waiting on user's agreement
  scripts/st2bootstrap-deb.sh
  scripts/st2bootstrap-deb.template.sh
Labels: bash installer, feature

#682 Add extra flag for Ubuntu 16.04 to install py3 PPA automatically
  scripts/st2_bootstrap.sh
  scripts/st2bootstrap-deb.sh
  scripts/st2bootstrap-deb.template.sh
Labels: bash installer, bug

#680 Remove st2debug component
  packages/st2/debian/st2.links
  packages/st2/in-requirements.txt
  rake/build/environment.rb
  rake/spec/spec_helper.rb
Labels: enhancement, refactor

#683 Remove st2 resultstracker
  packages/st2/Makefile
  packages/st2/debian/rules
  packages/st2/debian/st2resultstracker.service
  packages/st2/rpm/st2.spec
  packages/st2/rpm/st2resultstracker.service
  rake/spec/spec_helper.rb
Labels: enhancement
