Repository StackStorm/st2-packages, pull requests merged in 2020-04, with the labels that each got.

#639 Various fixes to the el8 installer script
  scripts/includes/common.sh
  scripts/includes/rhel.sh
  scripts/st2bootstrap-deb.sh
  scripts/st2bootstrap-el6.sh
  scripts/st2bootstrap-el7.sh
  scripts/st2bootstrap-el8.sh
Labels: bash installer

#640 Skip st2mistral check for el8 installer
  scripts/includes/rhel.sh
  scripts/st2bootstrap-el6.sh
  scripts/st2bootstrap-el7.sh
  scripts/st2bootstrap-el8.sh
Labels: bash installer, enhancement

#642 Fixing RHEL 6 and 7 not having repoquery -y
  scripts/includes/rhel.sh
  scripts/st2bootstrap-el6.sh
  scripts/st2bootstrap-el7.sh
  scripts/st2bootstrap-el8.sh
Labels: bash installer, bug
